### ISSUE TITLE
Any advantages over Cow<str>?

### ISSUE THREAD

**Issue by dtolnay** [dnsl48/twine#1]
It seems like `Cow<str>` is a more standard type for when string data may be either owned or borrowed.

```rust
// Is this just as good?
type Twine = Cow<'static, str>;
```

https://doc.rust-lang.org/std/borrow/enum.Cow.html

**Comment by dnsl48** [comment]
Hi dtolnay,

Well, the main purpose of this package is to be a specialisation over strings and hence provide string-specific methods, e.g. `as_bytes` and `as_ptr`. Although you're right, I probably could implement it as
```
struct Twine (Cow<'static, str>);
```

**Comment by dnsl48** [comment]
although now I see that Deref implementation probably makes those methods available even without a separate struct...

**Comment by dtolnay** [comment]
Yeah all the methods of `str` are available on `Cow<str>`.

```rust
use std::borrow::Cow::{self, Borrowed};

type Twine = Cow<'static, str>;

fn main() {
    let twine: Twine = Borrowed("dnsl48");
    println!("{:?}", twine.as_bytes());
}
```

**Comment by dnsl48** [comment]
Well, there is still another downside of having it aliased. It doesn't make it that smooth in pattern matching - we still have to import `Cow::Borrowed` and `Cow::Owned`

**Comment by dnsl48** [comment]
well, thank you for getting my head right!
Cow is a bit more obscure and it's not really documented in the rust book, but it's a part of the std library, so I believe it should really be used instead of this crate.
Since there is no real point for this crate, I'm gonna deprecate it :)
